CREATE TABLE person (
    id INTEGER PRIMARY KEY,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    age INTEGER
);
select * from person where first_name = james;

--see how many customers are in our table:
select count(*) as "Customer Count" from customers;

--how many unique companies are in our table?
select count(distinct company)as "Distinct Companies" from customers ;

--add a column for the CompanyID to the customers table
alter table customers add CompanyID int;

--notice that the companyId is null
select companyID, company from customers;

--create a table for the companies
--this statement will also create a companyID column which will
--increment when you insert a new record
create table Companies (
companyID number generated by default on null as identity,
Company varchar(50)
);

--see what's in your companies table now
select * from Companies;

--add a test company to verify that the identity field works
insert into companies(Company)values ('James Company');

--add unique companies from customers to the company table
insert into Companies (Company) select distinct company from customers;

--look at what you've done
select * from Companies;
--another way to select is to list the fields
select companyID, Company from customers;

--update the compnayId in the customers table
update customers c set c.companyID = (select t.companyID from
Companies t where t.company=c.company);

select * from customers;

--query to check your data
select c.companyID,c.company,t.companyID,t.Company from
customers c inner join Companies t on c.CompanyID=t.CompanyID;

--remove the company column from the customers table. It is no longer needed
alter table customers drop column company;

--notice you won't see the company column
select * from customers;

-- a query to bring it all back together
select fullname, company from customers 
inner join companies on 
customers.companyid=companies.companyid;

drop table customers;
delete from companies where companyid > 1019;

----------  Day 4 Nov 14 ----
-------- created citites table n inserted data from customesrs table ----
create table Cities (
CityID number generated by default on null as identity,
City varchar(50)
);

insert into Cities(City) select distinct city from customers;
select count(*) from cities;
select * from Cities;

select c.fullname, t.city from customers c inner join cities t on c.cityid = t.cityid;

-----------------  creating States and inserting data from customesrs then display the table ----------
create table States (
StateID number generated by default on null as identity,
State varchar(50)
);

insert into States(State) select distinct state from customers;
select * from States;

drop table positions;
create table Positions (
PositionID number generated by default on null as identity,
Position varchar(60)
);
select * from positions;

insert into Positions(Position) select distinct position from customers;


select * from positions;



--- adding a city id field in customers table ------
alter table customers add PositionID int;

update customers c set c.cityid = (Select t.cityid from cities t where t.city=c.city);
------  if too many records delete all the records and put in just a few as below -----
delete from citiets;
insert into cities (city) select distinct city from customers;

select * from companies where companyid=10;

